# Generated by Django 6.0.2 on 2026-02-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='carrer_level',
            new_name='career_level',
        ),
    ]
